# Site Settings
lang: en
title: Tunisians in Neuroscience and AI
tagline: TuNA
email: hamza.abdelhedii@gmail.com
description: >
  A community of Tunisians with an interest in neuroscience and AI.
baseurl: "/tunisians-neuroscience-ai"
url: "https://www.tunisiansneuroscienceai.com"
permalink: pretty
#favicon: /path/to/favicon.png
gh_sponsor: chrisrhymes
hide_share_buttons: false
theme_color: '#eb8686'
fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr
force_theme: light

paginate: 5
paginate_path: "/events/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: tuna

# Reading Files
include:
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass
  # load_paths: 
    # - node_modules

#google_analytics: UA-code-here
cookie_policy: /cookie-policy/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
      # hero_image: ./img/jetbrains-variant-4.svg

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

social:
  # facebook: https://www.facebook.com/
  # instagram: https://www.instagram.com/
  # threads: https://www.threads.net/
  # tiktok: https://www.tiktok.com/
  # x: https://www.x.com/
  # youtube: https://www.youtube.com/
  